name: Lifeline
main: MonoAdrian23\Lifeline
api: 3.0.0
mcpe-protocol: [408]
version: "1.0"
author: MonoAdrian23
commands:
  lifeline:
    description: "§bOnlinezeit Belohnungen"
    permission: "lifeline.use"
    aliases:
    - lf
    default: op

